/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex001;

import java.awt.Panel;
import java.sql.DatabaseMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author franz
 */
public class MainMenuDLG extends javax.swing.JDialog {

    private boolean ok = false;
    private String name = null;
    private int counter = 0;
    private DefaultListModel<String> dlm;

    public MainMenuDLG(java.awt.Frame parent, boolean modal) throws SQLException, Exception {
        super(parent, modal);
        initComponents();
        
        plLeaderboard.setVisible(false);

        dlm = new DefaultListModel<>();
        listLeaderboard.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        plMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btCancel = new javax.swing.JButton();
        tfName = new javax.swing.JTextField();
        btStart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        plLeaderboard = new javax.swing.JPanel();
        liLB = new javax.swing.JScrollPane();
        listLeaderboard = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(250, 400));
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        plMain.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        plMain.add(jLabel1, gridBagConstraints);

        btCancel.setText("CANCEL");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        plMain.add(btCancel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        plMain.add(tfName, gridBagConstraints);

        btStart.setText("START");
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onStart(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        plMain.add(btStart, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        plMain.add(jPanel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        plMain.add(jPanel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        plMain.add(jPanel5, gridBagConstraints);

        jButton1.setText("Leaderboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLeaderboard(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        plMain.add(jButton1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Steuerung: W, A, S, D");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        plMain.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        plMain.add(jPanel6, gridBagConstraints);

        jPanel1.add(plMain);

        plLeaderboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        plLeaderboard.setLayout(new java.awt.GridLayout(1, 0));

        listLeaderboard.setBorder(javax.swing.BorderFactory.createTitledBorder("Leaderboard"));
        listLeaderboard.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        liLB.setViewportView(listLeaderboard);

        plLeaderboard.add(liLB);

        jPanel1.add(plLeaderboard);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean isOk() {
        return ok;
    }
    private void onStart(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onStart
        name = tfName.getText();
        if(name == null || name.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Bitte gib einen Namen ein!");
            return;
        }
        ok = true;
        this.dispose();
    }//GEN-LAST:event_onStart

    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        System.exit(0);
    }//GEN-LAST:event_onCancel

    private void onLeaderboard(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLeaderboard
        if (counter == 0) {
            plLeaderboard.setVisible(true);
            counter++;
        } else if (counter == 1) {
            plLeaderboard.setVisible(false);
            counter = 0;
        }

    }//GEN-LAST:event_onLeaderboard

    String getPlayerName() {
        return name;
    }

    public void initializeLeaderboard(ArrayList<Player> players) throws Exception {
        for (int i = 0; i < players.size(); i++) {
            Player pl = players.get(i);
            dlm.addElement(pl.toString());
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane liLB;
    private javax.swing.JList<String> listLeaderboard;
    private javax.swing.JPanel plLeaderboard;
    private javax.swing.JPanel plMain;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
